import assert from "node:assert/strict";
import fs from "node:fs";
import { getCatalogueSourceContract, hasCatalogueSourceContract } from "../web/src/lib/automation/catalogue-source-contract";

const route = fs.readFileSync("web/src/app/api/automation/candidates/route.ts", "utf8");
const workflow = fs.readFileSync(".github/workflows/catalogue-discovery.yml", "utf8");
const liquorWorkflow = fs.readFileSync(".github/workflows/catalogue-victorian-liquor-licences.yml", "utf8");

assert.match(route, /AUTOMATION_INGEST_TOKEN/);
assert.match(route, /MAX_CANDIDATES = 100/);
assert.match(route, /getCatalogueSourceContract/);
assert.match(route, /hasCatalogueSourceContract/);
assert.match(route, /holdCatalogueSourceContract/);
assert.match(route, /markCatalogueSourceContractHealthy/);
assert.match(route, /Candidate processing was held; no listing changed/);
assert.match(route, /isAllowedCatalogueSourceUrl/);
assert.match(route, /Candidate source must match the approved source batch/);
assert(route.indexOf("hasCatalogueSourceContract") < route.indexOf("body.candidates"), "The source contract must be checked before candidate records are read.");
assert.match(route, /qualification_outcome: qualification\.outcome/);
assert.match(route, /listing_status: "published"/);
assert.match(route, /ownership_status: "unclaimed"/);
assert.match(route, /candidate_handoff_exception_created/);
assert.match(route, /existingRun\.status === "failed"/);
assert.match(route, /STALE_PROCESSING_MS/);
assert.match(route, /STALE_PROCESSING_MS = 30 \* 1000/);
assert.match(route, /staleProcessing/);
assert.match(route, /Could not resume the failed or stale candidate handoff run/);
assert.match(route, /Could not recover the partially completed qualified listing/);
assert.match(route, /loadCandidateDuplicateCandidates/);
assert.match(route, /Loading every listing for every singleton handoff made a 365-row official/);
assert.doesNotMatch(route, /function loadListings/);
assert.match(route, /qualifyCandidate as the final authority/);
assert.match(route, /A singleton retry is the durable recovery path/);
assert.match(route, /source_record_key/, "Singleton recovery must reuse existing private evidence.");
assert.match(route, /needsSourceRequalification/);
assert.match(route, /qualification_reasons\.includes\("unapproved_source"\)/);
assert.match(route, /enrichMatchingListing/);
assert.match(route, /approved_source_empty_field_enriched/);
assert.match(route, /owner_control_preserved: true/);
assert.match(route, /vendor\.ownership_status === "unclaimed" && !currentText/);
assert.match(route, /catalogue_field_conflicts/);
assert.match(route, /recordListingFieldEvidence/);
assert.match(route, /listing_field_evidence/);
assert.match(route, /freshness_due_at: freshnessDueAt/);
assert.match(route, /source\.refreshIntervalDays/);
assert.match(route, /application_state: fieldName === "trading_hours" \? "observed" : "applied"/);
assert.match(route, /tradingHours: optionalText\(item\.tradingHours\)/);
assert.doesNotMatch(route, /stripe/i);
assert.match(workflow, /candidate:handoff/);
assert.match(workflow, /AUTOMATION_INGEST_TOKEN/);
assert.match(liquorWorkflow, /npm run acquire:vic-liquor/);
assert.match(liquorWorkflow, /CATALOGUE_SOURCE: victorian_liquor_licences/);
assert.match(liquorWorkflow, /AUTOMATION_INGEST_TOKEN/);
const handoff = fs.readFileSync("scripts/submit-candidate-handoff.ts", "utf8");
const sourceContract = fs.readFileSync("web/src/lib/automation/catalogue-source-contract.ts", "utf8");
assert.match(handoff, /const BATCH_SIZE = 1/);
assert.match(handoff, /const MAX_CONCURRENT_BATCHES = 1/);
assert.match(handoff, /const REQUEST_SETTLE_DELAY_MS = 250/);
assert.match(handoff, /if \(!result\.idempotent\) await delay\(REQUEST_SETTLE_DELAY_MS\)/);
assert.match(handoff, /const MAX_ATTEMPTS = 9/);
assert.match(handoff, /\[429, 500, 502, 503, 504\]/);
assert.match(handoff, /response\.status === 202/);
assert.match(handoff, /sourceContractVersion: sourceContract\.version/);
assert.match(handoff, /sourceContractVersion: sourceContract\.version,\n\s*candidates,/);
assert.match(fs.readFileSync("scripts\/submit-candidate-handoff.ts", "utf8"), /await response\.text\(\)/);
assert.match(sourceContract, /openstreetmap-candidate-v1/);
assert.match(sourceContract, /victorian-liquor-licences-v2/);
assert.match(sourceContract, /refreshIntervalDays: 7/);
assert.match(sourceContract, /refreshIntervalDays: 31/);
const openStreetMap = getCatalogueSourceContract("openstreetmap");
assert(openStreetMap);
assert.equal(hasCatalogueSourceContract("openstreetmap", openStreetMap.version), true);
assert.equal(hasCatalogueSourceContract("openstreetmap", "openstreetmap-candidate-v0"), false);
assert.equal(getCatalogueSourceContract("unapproved-source"), null);

console.log("Candidate automation ingestion boundary checks passed.");
