import assert from "node:assert/strict";
import fs from "node:fs";
import { getCatalogueSourceContract, hasCatalogueSourceContract } from "../web/src/lib/automation/catalogue-source-contract";

const route = fs.readFileSync("web/src/app/api/automation/candidates/route.ts", "utf8");
const workflow = fs.readFileSync(".github/workflows/catalogue-discovery.yml", "utf8");
const liquorWorkflow = fs.readFileSync(".github/workflows/catalogue-victorian-liquor-licences.yml", "utf8");
const taxPractitionersBoardWorkflow = fs.readFileSync(".github/workflows/catalogue-tax-practitioners-board.yml", "utf8");
const outcomeRoute = fs.readFileSync("web/src/app/api/automation/catalogue-run-status/route.ts", "utf8");

assert.match(route, /AUTOMATION_INGEST_TOKEN/);
assert.match(route, /MAX_CANDIDATES = 100/);
assert.match(route, /getCatalogueSourceContract/);
assert.match(route, /hasCatalogueSourceContract/);
assert.match(route, /loadApprovedSourceRegistry/);
assert.match(route, /sourceRegistryMatchesContract/);
assert.match(route, /holdCatalogueSourceContract/);
assert.match(route, /markCatalogueSourceContractHealthy/);
assert.match(route, /finaliseStaleSourceRuns/);
assert.match(route, /Candidate handoff exceeded the processing window and was safely closed before a new source observation/);
assert.match(route, /Candidate processing was held; no listing changed/);
assert.match(route, /isAllowedCatalogueSourceUrl/);
assert.match(route, /Candidate source must match the approved source batch/);
assert(route.indexOf("hasCatalogueSourceContract") < route.indexOf("body.candidates"), "The source contract must be checked before candidate records are read.");
assert(route.indexOf("loadApprovedSourceRegistry") < route.indexOf("body.candidates"), "The durable source registry must be checked before candidate records are read.");
assert.match(route, /qualification_outcome: qualification\.outcome/);
assert.match(route, /listing_status: "published"/);
assert.match(route, /ownership_status: "unclaimed"/);
assert.match(route, /candidate_handoff_exception_created/);
assert.match(route, /existingRun\.status === "failed"/);
assert.match(route, /STALE_PROCESSING_MS/);
assert.match(route, /STALE_PROCESSING_MS = 60 \* 1000/);
assert.match(route, /staleProcessing/);
assert.match(route, /Could not resume the failed or stale candidate handoff run/);
assert.match(route, /Could not recover the partially completed qualified listing/);
assert.match(route, /loadCandidateDuplicateCandidates/);
assert.match(route, /Could not look up candidate source-record duplicates/);
assert.match(route, /\.eq\("source_url", candidate\.sourceUrl\)/);
assert.match(route, /Loading every listing for every singleton handoff made a 365-row official/);
assert.doesNotMatch(route, /function loadListings/);
assert.match(route, /qualifyCandidate as the final authority/);
assert.match(route, /Exact input retries remain idempotent through the source\/artifact run/);
assert.match(route, /existingRun\.status === "completed"/);
assert.match(route, /priorQualified/);
assert.match(route, /\.neq\("run_id", run\.id\)/);
assert.match(route, /refreshQualifiedSourceListing/);
assert.match(route, /approved_source_listing_refreshed/);
assert.match(route, /public_field_changes: appliedFields/);
assert.match(route, /owner_control_preserved: true/);
assert.match(route, /comparableFieldValue\(fieldName, currentText\) === comparableFieldValue\(fieldName, valueText\)/);
assert.match(route, /\["contact_email", "phone", "website", "description", "trading_hours"\]\.includes\(fieldName\)/);
assert.match(route, /enrichMatchingListing/);
assert.match(route, /approved_source_empty_field_enriched/);
assert.match(route, /duplicate_vendor_id/);
assert.match(route, /Could not recover matching-listing field evidence/);
assert.match(route, /hasExternalContactEmailAssignment/);
assert.match(route, /emailIsAssignedElsewhere/);
assert.match(route, /\.eq\("contact_email", email\)/);
assert.match(route, /\.neq\("id", vendorId\)/);
assert.match(route, /applicationState === "applied"/);
assert.match(route, /ignoreDuplicates: true/);
assert.match(route, /owner_control_preserved: true/);
assert.match(route, /vendor\.ownership_status === "unclaimed" && !currentText/);
assert.match(route, /catalogue_field_conflicts/);
assert.match(route, /recordListingFieldEvidence/);
assert.match(route, /listing_field_evidence/);
assert.match(route, /freshness_due_at: freshnessDueAt/);
assert.match(route, /source\.refreshIntervalDays/);
assert.match(route, /application_state: "applied"/);
assert.match(route, /tradingHours: optionalTradingHours\(item\.tradingHours\)/);
assert.match(route, /description: optionalDescription\(item\.description\)/);
assert.match(route, /function optionalTradingHours/);
assert.match(route, /\["description", input\.candidate\.description\]/);
assert.match(route, /vendor\.ownership_status === "unclaimed" && !currentText/);
assert.match(route, /permitted_use === "store_and_display"/);
assert.match(route, /registry\.automated === true/);
assert.match(route, /registry\.enabled === true/);
assert.match(route, /sameHosts\(registry\.allowed_hosts, source\.allowedHosts\)/);
assert.doesNotMatch(route, /stripe/i);
assert.match(workflow, /candidate:handoff/);
assert.match(workflow, /AUTOMATION_INGEST_TOKEN/);
assert.match(workflow, /max-parallel: 1/);
assert.match(workflow, /shard_index: \[0, 1, 2, 3, 4, 5, 6, 7\]/);
assert.match(workflow, /--shard-count 8/);
assert.match(workflow, /record-handoff-outcome/);
assert.match(workflow, /catalogue-run-status/);
assert.match(liquorWorkflow, /npm run acquire:vic-liquor/);
assert.match(liquorWorkflow, /CATALOGUE_SOURCE: victorian_liquor_licences/);
assert.match(liquorWorkflow, /AUTOMATION_INGEST_TOKEN/);
assert.match(taxPractitionersBoardWorkflow, /npm run acquire:tpb/);
assert.match(taxPractitionersBoardWorkflow, /CATALOGUE_SOURCE: tax_practitioners_board/);
assert.match(taxPractitionersBoardWorkflow, /Individual-agent data never enters the CSV, artifact or public directory/);
assert.match(taxPractitionersBoardWorkflow, /AUTOMATION_INGEST_TOKEN/);
const handoff = fs.readFileSync("scripts/submit-candidate-handoff.ts", "utf8");
const sourceContract = fs.readFileSync("web/src/lib/automation/catalogue-source-contract.ts", "utf8");
const discoveryWorkflow = fs.readFileSync(".github/workflows/catalogue-discovery.yml", "utf8");
assert.match(handoff, /const BATCH_SIZE = 1/);
assert.match(handoff, /const MAX_CONCURRENT_BATCHES = 1/);
assert.match(handoff, /--shard-index/);
assert.match(handoff, /--shard-count/);
assert.match(handoff, /index % shardCount === shardIndex/);
assert.match(handoff, /Sharding preserves every singleton/);
assert.match(handoff, /const REQUEST_SETTLE_DELAY_MS = 1_000/);
assert.match(handoff, /const REQUEST_TIMEOUT_MS = 45_000/);
assert.match(handoff, /AbortSignal\.timeout\(REQUEST_TIMEOUT_MS\)/);
assert.match(handoff, /did not receive a response after/);
assert.match(handoff, /if \(!result\.idempotent\) await delay\(REQUEST_SETTLE_DELAY_MS\)/);
assert.match(handoff, /const MAX_ATTEMPTS = 18/);
assert.match(handoff, /\[429, 500, 502, 503, 504\]/);
assert.match(handoff, /response\.status === 202/);
assert.match(handoff, /sourceContractVersion: sourceContract\.version/);
assert.match(handoff, /sourceContractVersion: sourceContract\.version,\n\s*candidates,/);
assert.match(fs.readFileSync("scripts\/submit-candidate-handoff.ts", "utf8"), /await response\.text\(\)/);
assert.match(sourceContract, /openstreetmap-candidate-v1/);
assert.match(sourceContract, /victorian-liquor-licences-v2/);
assert.match(sourceContract, /tax-practitioners-board-org-v1/);
assert.match(sourceContract, /refreshIntervalDays: 7/);
assert.match(discoveryWorkflow, /timeout-minutes: 75/);
assert.match(sourceContract, /refreshIntervalDays: 31/);
const taxPractitionersBoard = getCatalogueSourceContract("tax_practitioners_board");
assert(taxPractitionersBoard);
assert.equal(hasCatalogueSourceContract("tax_practitioners_board", taxPractitionersBoard.version), true);
const openStreetMap = getCatalogueSourceContract("openstreetmap");
assert(openStreetMap);
assert.equal(hasCatalogueSourceContract("openstreetmap", openStreetMap.version), true);
assert.equal(hasCatalogueSourceContract("openstreetmap", "openstreetmap-candidate-v0"), false);
assert.equal(getCatalogueSourceContract("unapproved-source"), null);
assert.match(outcomeRoute, /AUTOMATION_INGEST_TOKEN/);
assert.match(outcomeRoute, /getCatalogueSourceContract/);
assert.match(outcomeRoute, /catalogue_source_handoff_failed/);
assert.match(outcomeRoute, /listing_state_changed_by_status_callback: false/);
assert.match(outcomeRoute, /integration_health/);

console.log("Candidate automation ingestion boundary checks passed.");
