import assert from "node:assert/strict";
import fs from "node:fs";

const migration = fs.readFileSync("supabase/migrations/20260827141339_catalogue_source_evidence_lifecycle.sql", "utf8");

assert.match(migration, /CREATE TABLE public\.catalogue_sources/);
assert.match(migration, /openstreetmap-candidate-v1/);
assert.match(migration, /victorian-liquor-licences-v1/);
const correction = fs.readFileSync("supabase/migrations/20260828015545_revise_victorian_liquor_source_contract.sql", "utf8");
const taxPractitionersBoard = fs.readFileSync("supabase/migrations/20260831100000_add_tax_practitioners_board_source.sql", "utf8");
const asicCreditLicensees = fs.readFileSync("supabase/migrations/20260901210000_add_asic_credit_licensee_source.sql", "utf8");
const geoscapeLocalities = fs.readFileSync("supabase/migrations/20260901220000_add_geoscape_locality_evidence_source.sql", "utf8");
const socialProfiles = fs.readFileSync("supabase/migrations/20260901230000_add_moderated_source_social_links.sql", "utf8");
const officialWebsiteFoundation = fs.readFileSync("supabase/migrations/20260904130841_official_website_enrichment_foundation.sql", "utf8");
assert.match(correction, /victorian-liquor-licences-v2/);
assert.match(correction, /unapproved_source/);
assert.match(taxPractitionersBoard, /tax_practitioners_board/);
assert.match(taxPractitionersBoard, /Creative Commons Attribution 4\.0 International/);
assert.match(taxPractitionersBoard, /store_and_display/);
assert.match(taxPractitionersBoard, /organisation records only/);
assert.match(taxPractitionersBoard, /must never store individual-agent/);
assert.match(asicCreditLicensees, /asic_credit_licensees/);
assert.match(asicCreditLicensees, /Creative Commons Attribution 3\.0 Australia/);
assert.match(asicCreditLicensees, /store_and_display/);
assert.match(asicCreditLicensees, /must never retain an individual licensee name/);
assert.match(geoscapeLocalities, /geoscape_vic_localities/);
assert.match(geoscapeLocalities, /Creative Commons Attribution 4\.0 International/);
assert.match(geoscapeLocalities, /supporting boundary reference only/);
assert.match(geoscapeLocalities, /cannot independently produce a business candidate/);
assert.match(socialProfiles, /direct social-profile link/);
assert.match(socialProfiles, /never crawls, embeds, stores, or displays third-party content/);
assert.match(socialProfiles, /ADD COLUMN IF NOT EXISTS facebook_url TEXT/);
assert.match(socialProfiles, /ADD COLUMN IF NOT EXISTS instagram_url TEXT/);
assert.match(socialProfiles, /facebook_url.*instagram_url/s);
assert.match(socialProfiles, /openstreetmap-candidate-v2/);
assert.match(socialProfiles, /CREATE OR REPLACE VIEW public\.published_vendors/);
assert.match(socialProfiles, /vendor\.facebook_url/);
assert.match(socialProfiles, /vendor\.instagram_url/);
assert.match(officialWebsiteFoundation, /official_business_site/);
assert.match(officialWebsiteFoundation, /official-business-site-pilot-v1/);
assert.match(officialWebsiteFoundation, /'evidence_only'/);
assert.match(officialWebsiteFoundation, /automated = false/);
assert.match(officialWebsiteFoundation, /enabled = false/);
assert.match(officialWebsiteFoundation, /CREATE TABLE public\.official_website_inspections/);
assert.match(officialWebsiteFoundation, /robots_status/);
assert.match(officialWebsiteFoundation, /terms_review_status/);
assert.match(officialWebsiteFoundation, /content_fingerprint/);
assert.match(officialWebsiteFoundation, /'service', 'booking_url', 'menu_url',\s*'area_served', 'accessibility'/s);
assert.match(officialWebsiteFoundation, /ENABLE ROW LEVEL SECURITY/);
assert.match(officialWebsiteFoundation, /REVOKE ALL ON TABLE public\.official_website_inspections FROM PUBLIC, anon, authenticated/);
assert.match(officialWebsiteFoundation, /GRANT ALL ON TABLE public\.official_website_inspections TO service_role/);
const freshnessBackfill = fs.readFileSync("supabase/migrations/20260828021000_backfill_catalogue_evidence_freshness.sql", "utf8");
assert.match(freshnessBackfill, /freshness_due_at/);
assert.match(freshnessBackfill, /interval '7 days'/);
assert.match(freshnessBackfill, /interval '31 days'/);
assert.match(freshnessBackfill, /not alter a public listing field/);
const completedFreshnessBackfill = fs.readFileSync("supabase/migrations/20260829090000_complete_catalogue_evidence_freshness_backfill.sql", "utf8");
assert.match(completedFreshnessBackfill, /freshness_due_at IS NULL/);
assert.match(completedFreshnessBackfill, /without changing any public field or listing state/);
assert.match(migration, /Creative Commons Attribution 4\.0 International/);
assert.match(migration, /source_contract_version TEXT/);
assert.match(migration, /CREATE TABLE public\.listing_field_evidence/);
assert.match(migration, /field_name IN \('business_name'.*'trading_hours'\)/s);
assert.match(migration, /CREATE TABLE public\.catalogue_field_conflicts/);
assert.match(migration, /ENABLE ROW LEVEL SECURITY/g);
assert.match(migration, /REVOKE ALL ON TABLE[\s\S]+FROM PUBLIC, anon, authenticated/);
assert.match(migration, /GRANT ALL ON TABLE[\s\S]+TO service_role/);
assert.doesNotMatch(migration, /GRANT .* TO (anon|authenticated)/);
console.log("Catalogue source evidence lifecycle checks passed.");
