import assert from "node:assert/strict";
import fs from "node:fs";
import { normaliseSubmissionWebsite } from "../web/src/lib/submission-input";

const migration = fs.readFileSync("supabase/migrations/20260722003158_owner_submitted_business_candidate.sql", "utf8");
const actions = fs.readFileSync("web/src/app/(directory)/join/actions.ts", "utf8");
const join = fs.readFileSync("web/src/app/(directory)/join/page.tsx", "utf8");
const ownerForm = fs.readFileSync("web/src/app/(directory)/join/OwnerSubmissionForm.tsx", "utf8");
const controls = fs.readFileSync("web/src/app/(directory)/join/JoinFormControls.tsx", "utf8");
const ownerEmailFix = fs.readFileSync("supabase/migrations/20260804205239_fix_owner_submission_email_validation.sql", "utf8");

assert.match(migration, /auth\.uid\(\)/);
assert.match(migration, /INSERT INTO public\.claim_requests/);
assert.match(migration, /'owner_submitted_candidate', true/);
assert.match(migration, /SET ownership_status = 'claim_pending'/);
assert.match(migration, /'publication_unchanged', true/);
assert.match(migration, /GRANT EXECUTE ON FUNCTION public\.submit_owned_business_candidate_for_current_user[\s\S]*TO authenticated/);
assert.match(actions, /submit_owned_business_candidate_for_current_user/);
assert.match(actions, /createClient\(\)/);
assert.match(actions, /verifyTurnstileToken\(fields\.token, "business_submission"\)/);
assert.match(actions, /OwnerSubmissionState/);
assert.match(join, /I own or represent it/);
assert.match(join, /Suggest a local business/);
assert.match(join, /rpc\("search_published_vendors"/, "Find-first must reuse the safe public typo and intent reader rather than a second literal-only lookup.");
assert.match(join, /p_suburb_slug: suburb \|\| null/, "Owner search may search all Darebin before a suburb is known, while retaining an optional suburb filter.");
assert.match(join, /Any Darebin suburb/, "Suburb must be optional while checking for an existing listing.");
assert.match(join, /View profile/, "Possible matches must be inspectable before a claim or missing-business path.");
assert.match(join, /match\.is_claimed/, "A claimed match must offer ownership help instead of a misleading new claim action.");
assert.doesNotMatch(join, /\.ilike\("business_name"/, "The owner find-first route must not fall back to an isolated literal-only name search.");
assert.match(ownerForm, /Submit business and ownership request/);
assert.match(join, /CategoryField/);
assert.match(join, /Submitting securely/);
assert.match(join, /min-w-0/);
assert.match(join, /OwnerSubmissionForm/);
assert.match(join, /TurnstileField/);
assert.match(join, /dogtrainersdirectory\.com\.au/);
assert.match(ownerForm, /block min-w-0/);
assert.match(ownerForm, /grid-cols-1/);
assert.match(join, /grid-cols-1/);
assert.match(ownerForm, /TurnstileField/);
assert.match(ownerForm, /Your entered details are still here/);
assert.match(actions, /values: OwnerSubmissionValues/);
assert.match(ownerForm, /defaultValue=\{state\.values\.submitterName\}/);
assert.match(ownerForm, /defaultValue=\{state\.values\.relationshipExplanation\}/);
assert.match(ownerForm, /defaultValue=\{state\.values\.suburbSlug\}/);
assert.match(ownerForm, /name="relationshipExplanation"/);
assert.match(ownerForm, /minLength=\{10\}/);
assert.match(controls, /w-full whitespace-normal sm:w-auto/);
assert.match(controls, /Complete human verification before submitting/);
assert.match(controls, /turnstile-verification-change/);
assert.match(controls, /onError=\{unavailable\}/);
assert.match(controls, /Human verification could not load\. Check your connection and refresh it\./);
assert.match(controls, /window\.setTimeout/);
assert.equal(normaliseSubmissionWebsite("dogtrainersdirectory.com.au"), "https://dogtrainersdirectory.com.au/");
assert.equal(normaliseSubmissionWebsite("http://example.com/path"), "https://example.com/path");
assert.equal(normaliseSubmissionWebsite("https://example.com"), "https://example.com/");
assert.match(ownerEmailFix, /p_submitter_email/);
assert(!ownerEmailFix.includes("\\\\."), "Owner submission email validation must use a single regex escape for the dot.");
for (const forbidden of ["is_published = true", "SET owner_id =", "is_claimed = true", "TO anon"]) {
  assert(!migration.includes(forbidden), `Owner candidate flow must not contain ${forbidden}.`);
}
console.log("Owner-submitted business candidate boundary checks passed.");
