import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/20260722023000_moderated_owner_media.sql"), "utf8");
const ownerRoute = fs.readFileSync(path.join(root, "web/src/app/api/owner/media/route.ts"), "utf8");
const ownerPreviewRoute = fs.readFileSync(path.join(root, "web/src/app/api/owner/media/[proposalId]/route.ts"), "utf8");
const publicRoute = fs.readFileSync(path.join(root, "web/src/app/api/media/[mediaId]/route.ts"), "utf8");
const proposalForm = fs.readFileSync(path.join(root, "web/src/app/(directory)/dashboard/MediaProposalForm.tsx"), "utf8");
const websiteProposalForm = fs.readFileSync(path.join(root, "web/src/app/(directory)/dashboard/WebsiteMediaProposalForm.tsx"), "utf8");
const websitePreviewRoute = fs.readFileSync(path.join(root, "web/src/app/api/owner/media/website-preview/route.ts"), "utf8");
const websiteMediaUtility = fs.readFileSync(path.join(root, "web/src/lib/owner-website-media.ts"), "utf8");
const browserAcceptance = fs.readFileSync(path.join(root, "scripts/d017-browser-acceptance.mjs"), "utf8");

assert.match(migration, /'owner-media-proposals', 'owner-media-proposals', false, 2097152/);
assert.match(migration, /REVOKE ALL ON TABLE public\.listing_media_proposals FROM PUBLIC, anon, authenticated/);
assert.match(migration, /private\.require_active_operator\(\)/);
assert.match(migration, /publication_unchanged/);
assert.doesNotMatch(migration, /UPDATE public\.vendors/);
assert.match(ownerRoute, /imageContentType\(bytes\)/);
assert.match(ownerRoute, /const admin = createAdminClient\(\)/);
assert.match(ownerRoute, /admin\.storage\.from\("owner-media-proposals"\)\.upload/);
assert.match(ownerRoute, /Only the claimed owner can propose media/);
assert.match(ownerPreviewRoute, /list_current_owner_media_proposals/);
assert.match(ownerPreviewRoute, /proposal\.proposal_id === proposalId/);
assert.match(ownerPreviewRoute, /Cache-Control": "private, no-store"/);
assert.doesNotMatch(ownerPreviewRoute, /getPublicUrl/);
assert.match(proposalForm, /const form = event\.currentTarget/);
assert.match(proposalForm, /new FormData\(form\)/);
assert.match(proposalForm, /form\.reset\(\)/);
assert.match(websiteProposalForm, /Find website images/);
assert.match(websiteProposalForm, /I am authorised to ask SuburbMates/);
assert.match(websiteProposalForm, /Rights attestation/);
assert.match(websitePreviewRoute, /supabase\.auth\.getUser\(\)/);
assert.match(websitePreviewRoute, /list_current_owner_vendors_with_channels/);
assert.match(websitePreviewRoute, /private, no-store/);
assert.match(websiteMediaUtility, /MAX_BYTES = 2 \* 1024 \* 1024/);
assert.match(websiteMediaUtility, /sameOwnerWebsiteHost/);
assert.match(websiteMediaUtility, /redirect: "manual"/);
assert.match(publicRoute, /NEXT_PUBLIC_PUBLIC_LAUNCH_ENABLED !== "true"/);
assert.match(publicRoute, /resolve_public_media/);
assert.doesNotMatch(ownerRoute, /getPublicUrl/);
assert.match(browserAcceptance, /D017_BROWSER_SCOPE must be all, public, owner, media, contact, or operator/);
assert.match(browserAcceptance, /Submit for review/);
assert.match(browserAcceptance, /Approve media/);
assert.match(browserAcceptance, /Remove media/);
assert.match(browserAcceptance, /only after operator approval/);
assert.match(browserAcceptance, /absent from the controlled public profile/);

console.log("Owner media privacy and holding-gate boundary checks passed.");
