import assert from "node:assert/strict";
import fs from "node:fs";

const migration = fs.readFileSync("supabase/migrations/20260827141339_catalogue_source_evidence_lifecycle.sql", "utf8");

assert.match(migration, /CREATE TABLE public\.catalogue_sources/);
assert.match(migration, /openstreetmap-candidate-v1/);
assert.match(migration, /victorian-liquor-licences-v1/);
const correction = fs.readFileSync("supabase/migrations/20260828015545_revise_victorian_liquor_source_contract.sql", "utf8");
const taxPractitionersBoard = fs.readFileSync("supabase/migrations/20260831100000_add_tax_practitioners_board_source.sql", "utf8");
assert.match(correction, /victorian-liquor-licences-v2/);
assert.match(correction, /unapproved_source/);
assert.match(taxPractitionersBoard, /tax_practitioners_board/);
assert.match(taxPractitionersBoard, /Creative Commons Attribution 4\.0 International/);
assert.match(taxPractitionersBoard, /store_and_display/);
assert.match(taxPractitionersBoard, /organisation records only/);
assert.match(taxPractitionersBoard, /must never store individual-agent/);
const freshnessBackfill = fs.readFileSync("supabase/migrations/20260828021000_backfill_catalogue_evidence_freshness.sql", "utf8");
assert.match(freshnessBackfill, /freshness_due_at/);
assert.match(freshnessBackfill, /interval '7 days'/);
assert.match(freshnessBackfill, /interval '31 days'/);
assert.match(freshnessBackfill, /not alter a public listing field/);
const completedFreshnessBackfill = fs.readFileSync("supabase/migrations/20260829090000_complete_catalogue_evidence_freshness_backfill.sql", "utf8");
assert.match(completedFreshnessBackfill, /freshness_due_at IS NULL/);
assert.match(completedFreshnessBackfill, /without changing any public field or listing state/);
assert.match(migration, /Creative Commons Attribution 4\.0 International/);
assert.match(migration, /source_contract_version TEXT/);
assert.match(migration, /CREATE TABLE public\.listing_field_evidence/);
assert.match(migration, /field_name IN \('business_name'.*'trading_hours'\)/s);
assert.match(migration, /CREATE TABLE public\.catalogue_field_conflicts/);
assert.match(migration, /ENABLE ROW LEVEL SECURITY/g);
assert.match(migration, /REVOKE ALL ON TABLE[\s\S]+FROM PUBLIC, anon, authenticated/);
assert.match(migration, /GRANT ALL ON TABLE[\s\S]+TO service_role/);
assert.doesNotMatch(migration, /GRANT .* TO (anon|authenticated)/);
console.log("Catalogue source evidence lifecycle checks passed.");
