import assert from "node:assert/strict";
import fs from "node:fs";

const work = fs.readFileSync("web/src/lib/ops/work.ts", "utf8");
const layout = fs.readFileSync("web/src/app/ops/layout.tsx", "utf8");
const page = fs.readFileSync("web/src/app/ops/page.tsx", "utf8");
const businesses = fs.readFileSync("web/src/app/ops/listings/page.tsx", "utf8");
const system = fs.readFileSync("web/src/app/ops/system/page.tsx", "utf8");
const listingDetail = fs.readFileSync("web/src/app/ops/listings/[vendorId]/page.tsx", "utf8");
const ownerDashboard = fs.readFileSync("web/src/app/(directory)/dashboard/page.tsx", "utf8");
const registerMigration = fs.readFileSync("supabase/migrations/20260725120000_alphabetical_ops_business_register.sql", "utf8");
const globalStyles = fs.readFileSync("web/src/app/globals.css", "utf8");
const navigationMigration = fs.readFileSync("supabase/migrations/20260725133000_complete_ops_navigation_filters.sql", "utf8");
const claimDetail = fs.readFileSync("web/src/app/ops/claims/[claimId]/page.tsx", "utf8");
const profileDetail = fs.readFileSync("web/src/app/ops/profile-edits/[requestId]/page.tsx", "utf8");
const contactDetail = fs.readFileSync("web/src/app/ops/contact/[requestId]/page.tsx", "utf8");
const listingDetailPage = fs.readFileSync("web/src/app/ops/listings/[vendorId]/page.tsx", "utf8");
const decisionReasonField = fs.readFileSync("web/src/components/ops/DecisionReasonField.tsx", "utf8");

assert.match(layout, /Work/);
assert.match(layout, /Businesses/);
assert.match(layout, /System/);
assert.doesNotMatch(layout, />Candidates</);
assert.doesNotMatch(layout, />Catalogue review</);
assert.match(page, /All open work/);
assert.match(page, /Open work list/);
assert.match(page, /Act now/);
assert.match(page, /Needs a decision/);
assert.match(page, /Later review/);
assert.match(work, /possible_duplicate/);
assert.match(work, /qualification_reasons\.length === 1/);
assert.match(work, /"act_now"/);
assert.match(work, /"needs_decision"/);
assert.match(work, /"later_review"/);
assert.match(page, /ops_list_candidate_handoff_records/);
assert.match(page, /ops_list_existing_catalogue_requalification_exceptions/);
assert.match(businesses, /Business register/);
assert.match(businesses, /"all"/);
assert.match(businesses, /ownership/);
assert.match(businesses, /source/);
assert.doesNotMatch(businesses, /Tier: \{listing\.tier\}/);
assert.match(work, /\/ops\/candidates\/\$\{item\.record_id\}/);
assert(fs.existsSync("web/src/app/ops/candidates/[recordId]/page.tsx"), "Work candidate rows need a route to the selected evidence and permitted action.");
assert.match(registerMigration, /PERFORM private\.require_active_operator\(\)/);
assert.match(registerMigration, /CASE WHEN v_status = 'all' THEN vendor\.business_name END ASC/);
assert.match(navigationMigration, /p_ownership_status TEXT DEFAULT NULL/);
assert.match(navigationMigration, /p_listing_source TEXT DEFAULT NULL/);
assert.match(navigationMigration, /p_record_id UUID DEFAULT NULL/);
assert.match(system, /Commercial readiness/);
assert.match(system, /Billing is off/);
assert.doesNotMatch(listingDetail, /listing\.tier|Premium presentation/, "Ops detail must not expose a billing presentation while billing is off.");
assert.doesNotMatch(ownerDashboard, /vendor\.tier|>Premium</, "Owner dashboard must not advertise an unapproved paid tier.");
assert.match(globalStyles, /@layer base\s*\{[\s\S]*?a\s*\{[\s\S]*?color:\s*inherit;/);
for (const forbidden of ["work_items", "realtime", "Stripe checkout", "subscription", "invoice", "ABN request"]) {
  assert(!page.includes(forbidden) && !work.includes(forbidden), `Ops Work must not introduce ${forbidden}`);
}
for (const [name, source] of [["claim", claimDetail], ["profile edit", profileDetail], ["contact", contactDetail]] as const) {
  assert.match(source, /DecisionReasonField/, `${name} review must offer editable reason presets`);
  assert.match(source, /Decision recorded with an immutable audit event\./, `${name} review must confirm immutable audit evidence`);
  assert((source.match(/← Back to/g) ?? []).length >= 2, `${name} review must provide top and bottom return links`);
}
assert.match(decisionReasonField, /type="button"/, "reason presets must not submit a decision themselves");
assert.match(decisionReasonField, /name="reason"/, "reason presets must preserve the required server-action field name");
assert.match(decisionReasonField, /onChange/, "operators must be able to edit a selected preset");
assert.match(claimDetail, /Recorded email match/, "claim review must show the exact email-match evidence without overclaiming authority");
assert.match(profileDetail, /Live state: no conflicts/, "profile review must surface a non-stale status");
assert.match(contactDetail, /actionClass/, "contact actions must distinguish positive, neutral, and destructive choices");
assert.match(listingDetailPage, /Decision recorded with an immutable audit event\./, "listing decisions must confirm immutable audit evidence");
assert((listingDetailPage.match(/← Back to businesses/g) ?? []).length >= 2, "listing detail must provide top and bottom return links");
console.log("Ops workspace boundary checks passed.");
