import assert from "node:assert/strict";
import fs from "node:fs";

const migration = fs.readFileSync("supabase/migrations/20260827142810_public_directory_intent_search.sql", "utf8");
const refinement = fs.readFileSync("supabase/migrations/20260827143425_refine_resolved_directory_intent.sql", "utf8");
const expansion = fs.readFileSync("supabase/migrations/20260828145153_expand_directory_intent_language.sql", "utf8");
const specificity = fs.readFileSync("supabase/migrations/20260830105746_prefer_specific_directory_intent.sql", "utf8");
const venueCoverage = fs.readFileSync("supabase/migrations/20260830143000_expand_osm_venue_coverage.sql", "utf8");
const specificityFix = fs.readFileSync("supabase/migrations/20260901100000_fix_directory_intent_specificity.sql", "utf8");

assert.match(migration, /CREATE OR REPLACE FUNCTION public\.search_published_vendors/);
assert.match(migration, /FROM public\.published_vendors AS vendor/);
assert.doesNotMatch(migration, /FROM public\.vendors\b/);
assert.match(migration, /SECURITY INVOKER/);
assert.match(migration, /SET search_path = ''/);
assert.match(migration, /\('pets', 'pet'\)/);
assert.match(migration, /\('antique', 'antiques'\)/);
assert.match(migration, /\('vet', 'veterinary'\)/);
assert.match(migration, /stores no query text|never retained/i);
assert.match(migration, /ORDER BY match_priority, match_distance ASC, business_name ASC, id ASC/);
assert.match(migration, /GRANT EXECUTE[\s\S]*TO anon, authenticated, service_role/);
assert.match(refinement, /RENAME TO search_published_vendors_literal_fallback/);
assert.match(refinement, /FROM public\.published_vendors AS vendor/);
assert.match(refinement, /WHERE vendor\.category_slug IN \(SELECT target_category_slug FROM resolved_categories\)/);
assert.match(refinement, /WHERE NOT EXISTS \(SELECT 1 FROM resolved_categories\)/);
assert.match(refinement, /REVOKE ALL ON FUNCTION public\.search_published_vendors_literal_fallback/);
assert.match(expansion, /CREATE OR REPLACE FUNCTION public\.search_published_vendors/);
assert.match(expansion, /FROM public\.published_vendors AS vendor/);
assert.doesNotMatch(expansion, /FROM public\.vendors\b/);
assert.match(expansion, /SECURITY INVOKER/);
assert.match(expansion, /\('mechanic', 'car-repair'\)/);
assert.match(expansion, /\('grocery', 'supermarket'\)/);
assert.match(expansion, /\('nails', 'beauty'\)/);
assert.match(expansion, /\('takeaway', 'fast-food'\)/);
assert.match(expansion, /Query text is never retained/);
assert.match(expansion, /REVOKE ALL ON FUNCTION public\.search_published_vendors/);
assert.match(specificity, /\('dog groomer', 'pet-grooming'\)/);
assert.match(specificity, /matched_intents AS/);
assert.match(specificity, /specificity = \(SELECT max\(specificity\) FROM matched_intents\)/);
assert.match(specificity, /SECURITY INVOKER/);
assert.match(specificity, /FROM public\.published_vendors AS vendor/);
assert.doesNotMatch(specificity, /FROM public\.vendors\b/);
assert.match(specificity, /Query text is never retained/);
assert.match(venueCoverage, /\('fitness', 'Fitness'/);
assert.match(venueCoverage, /\('dance-studio', 'Dance Studios'/);
assert.match(venueCoverage, /\('accommodation', 'Accommodation'/);
assert.match(venueCoverage, /\('gym', 'fitness'\)/);
assert.match(venueCoverage, /\('ballet', 'dance-studio'\)/);
assert.match(venueCoverage, /\('motel', 'accommodation'\)/);
assert.match(venueCoverage, /SECURITY INVOKER/);
assert.match(venueCoverage, /FROM public\.published_vendors AS vendor/);
assert.doesNotMatch(venueCoverage, /FROM public\.vendors\b/);
assert.match(venueCoverage, /Query text is never retained/);
assert.match(specificityFix, /\('dog groomer', 'pet-grooming'\)/);
assert.match(specificityFix, /cardinality\(string_to_array\(aliases\.alias, ' '\)\) AS specificity/);
assert.match(specificityFix, /specificity = \(SELECT max\(specificity\) FROM matched_intents\)/);
assert.match(specificityFix, /SECURITY INVOKER/);
assert.match(specificityFix, /FROM public\.published_vendors AS vendor/);
assert.doesNotMatch(specificityFix, /FROM public\.vendors\b/);
assert.match(specificityFix, /Query text is never retained/);
console.log("Directory intent-search policy checks passed.");
