import assert from "node:assert/strict";
import fs from "node:fs";
import { factualSummary, planOfficialWebsiteApplication } from "../web/src/lib/official-website-application-plan";

const vendor = { id: "vendor", business_name: "Example", website: "https://example.test", suburb_slug: "northcote", ownership_status: "unclaimed", description: null, contact_email: null, phone: "03 9000 0000", street_address: null, trading_hours: null, services: [], booking_url: null, menu_url: null, area_served: [], accessibility_features: [] };
const facts = [{ fieldName: "phone" as const, value: "03 9000 1111" }, { fieldName: "email" as const, value: "hello@example.test" }, { fieldName: "service" as const, value: "Sourdough baking" }, { fieldName: "service" as const, value: "Wedding cakes" }, { fieldName: "area_served" as const, value: "Darebin" }, { fieldName: "booking_url" as const, value: "https://example.test/book" }];
const plan = planOfficialWebsiteApplication(vendor, facts);
assert.equal(plan.updates.phone, undefined, "An existing field must never be overwritten.");
assert.deepEqual(plan.updates.services, ["Sourdough baking", "Wedding cakes"]);
assert.equal(plan.updates.booking_url, "https://example.test/book");
assert.equal(plan.updates.contact_email, "hello@example.test");
assert.ok(plan.facts.some((fact) => fact.fieldName === "contact_email"));
assert.ok(!plan.facts.some((fact) => fact.fieldName === "email"));
assert.ok(plan.conflictFields.includes("phone"));
assert.match(factualSummary(facts) ?? "", /Services include Sourdough baking, Wedding cakes\. Serves Darebin\./);
assert.doesNotMatch(JSON.stringify(plan), /image|marketing|testimonial/i);
const addressPlan = planOfficialWebsiteApplication(vendor, [{ fieldName: "street_address", value: "100 William Street, Sydney, NSW, 2000" }]);
assert.equal(addressPlan.updates.street_address, undefined, "A head-office address outside the listing locality must not publish.");
const runner = fs.readFileSync("web/src/lib/official-website-application.ts", "utf8");
const route = fs.readFileSync("web/src/app/api/automation/official-website-enrichment/route.ts", "utf8");
const workflow = fs.readFileSync(".github/workflows/official-website-enrichment.yml", "utf8");
assert.match(runner, /official-business-site-application-v3/);
assert.match(runner, /official_website_inspections/);
assert.match(runner, /freshness_due_at/);
assert.match(runner, /currentVendorIds/);
assert.match(runner, /catalogue_enrichment_runs!inner\(status\)/);
assert.match(runner, /catalogue_enrichment_runs\.status.*completed/);
assert.match(runner, /termsOverride/);
assert.match(runner, /staleBefore/);
assert.match(runner, /Execution ended before the bounded batch completed/);
assert.match(runner, /linked_page_application: "evidence_only"/);
assert.match(runner, /application_state: "observed"/);
assert.match(runner, /const homepageFacts = inspection\.facts\.filter/);
assert.match(runner, /planOfficialWebsiteApplication\(vendor, homepageFacts\)/);
assert.doesNotMatch(runner, /if \(!approvedHosts\.size\)/);
assert.match(route, /limit !== 1/);
assert.match(workflow, /cron: "13 20 \* \* \*"/);
assert.match(workflow, /seq 1 25/);
assert.match(workflow, /"\$batch"/);
assert.ok(workflow.includes('\\"limit\\":1'));
assert.doesNotMatch(workflow, /--retry/);
console.log("Official website application plans only factual empty-field enrichment and conflicts.");
