"use client";

import { useState } from "react";

export default function WebsiteMediaProposalForm({ vendorId, website }: { vendorId: string; website: string | null }) {
  const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false);
  if (!website) return null;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(null); const response = await fetch("/api/owner/media/from-website", { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json().catch(() => ({})); setPending(false); setMessage(response.ok ? "Your website image is private and awaiting operator review." : body.error || "We could not retrieve that image."); if (response.ok) window.location.assign(`/dashboard?media=submitted#media-${vendorId}`); }
  return <form onSubmit={submit} className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-5"><h4 className="font-black text-slate-950">Use an image from your website</h4><p className="mt-1 text-sm leading-6 text-slate-600">Paste an HTTPS image URL from your recorded website. By submitting, you confirm the business has permission for SuburbMates to copy and display it after review.</p><input type="hidden" name="vendorId" value={vendorId} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-800">Image URL<input required name="originUrl" type="url" placeholder="https://your-site/image.jpg" className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white p-3 font-normal" /></label><label className="text-sm font-bold text-slate-800">Image type<select name="mediaKind" className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white p-3 font-normal"><option value="listing_image">Listing image</option><option value="logo">Logo</option></select></label></div><label className="mt-4 block text-sm font-bold text-slate-800">Describe the image<input required name="altText" minLength={2} maxLength={160} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white p-3 font-normal" /></label><label className="mt-4 block text-sm font-bold text-slate-800">Rights attestation<textarea required name="sourceBasis" minLength={10} maxLength={1000} rows={3} defaultValue="I confirm this business has permission to reuse this exact website image on its SuburbMates profile." className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 font-normal" /></label>{message && <p role="status" className="mt-4 rounded-xl border border-slate-200 bg-white p-3 text-sm">{message}</p>}<button disabled={pending} className="btn btn-primary mt-4 min-h-11">{pending ? "Retrieving…" : "Copy privately for review"}</button></form>;
}
